# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties (version: compile; version_supported, version_filter: publish; lower, upper: excl. compat range)
minecraft_version = 26.1.2
minecraft_version_supported = [26.1, 26.1.2]
minecraft_version_filter = releases
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1
archives_base_name = MoreFishingRodVariants

# Mod Properties
mod_id = mstv-mfrv
mod_name = More (Fishing) Rod Variants (MStV+)
mod_name_short = More (Fishing) Rod Variants
mod_description = This mod adds more variants of the Fishing Rod and Carrot/Warped Fungus on a Stick item.
mod_version = 1.1.2
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
quad_version = 1.2.3
mstv_version = 1.4.14
mstv_version_id = 3WQJT5yT
tide_version_id = CIttOWbN